# Generated by Django 4.1.6 on 2023-05-11 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('resumer', models.TextField(blank=True)),
                ('contenu', models.TextField(blank=True)),
                ('auteur', models.CharField(max_length=60)),
                ('date_creer', models.DateField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_mise_en_vente', models.DateTimeField(null=True)),
                ('users', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Detail_car',
        ),
        migrations.DeleteModel(
            name='list_car',
        ),
    ]
